FROM python:3.12-slim

LABEL maintainer="Hrigoriu Programmer" email="Hrigoriu@gmail.com"
#MAINTAINER Hrigoriu Programmer "Hrigoriu@gmail.com" 
#стара форма, яка вже не підтримується, тому використовуємо LABEL

WORKDIR /app

# Копіюємо файл залежностей
COPY requirements.txt .

# Встановлюємо бібліотеки
RUN pip install --no-cache-dir -r requirements.txt

# Копіюємо решту файлів проекту
COPY . .

CMD [ "python", "app.py" ]



